#!/usr/bin/env python3
"""
Pull exact measurements out of the design boards.

The boards are HTML with every value inline, drawn at ship size. That makes them
a specification, not a mood board — and reading them beats eyeballing a token
list, which is how a screen ends up "close to but not perfect".

Writes one markdown reference per board into docs/screen-specs/.

    python3 scripts/extract-design.py
"""

from __future__ import annotations

import html
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "screen-specs"


def boards() -> pathlib.Path:
    """The design folder of the newest handoff bundle.

    Bundles arrive dated and cumulative, and the specs must be regenerated from
    the latest one — a spec extracted from a superseded board is worse than no
    spec, because it looks authoritative.
    """
    bundles = sorted((ROOT / "design").glob("handoff-*/design"))
    return bundles[-1] if bundles else ROOT / "design"

# A screen frame is the div drawn at the iPhone's logical size.
FRAME = re.compile(r"width:402px;height:874px")
# Every frame carries its own name: data-screen-label="H3b Hold in progress".
# Read that rather than the caption printed under the screen — a screen with no
# light twin has no caption at all, which is how H3b and H5 went missing.
# Ids come both ways round: N1c, T3b, E6 — and 1A, 1D on the history board.
LABEL = re.compile(r"data-screen-label=\"([A-Z]\d+[a-z]?|\d+[A-Z])\s+([^\"]{2,60})\"")
ELEMENT = re.compile(r"<(\w+)[^>]*?style=\"([^\"]+)\"[^>]*>([^<]{0,60})")


def tidy(style: str) -> str:
    """Collapse a style attribute to something readable in a table cell."""
    s = re.sub(r"\s+", " ", style).strip().rstrip(";")
    # The font shorthand repeats on every element and drowns everything else.
    s = re.sub(r"-apple-system,\s*'[^']*',\s*'?[^;]*?sans-serif", "", s)
    s = re.sub(r"\s*;\s*", " · ", s)
    return s.strip(" ·")


def screens(doc: str) -> list[tuple[str, str, int]]:
    """Every labelled screen, with where its frame starts."""
    found = []
    for m in LABEL.finditer(doc):
        frame = FRAME.search(doc, m.end())
        if frame:
            found.append((m.group(1), m.group(2).strip(), frame.start()))
    # The same screen appears twice per board, dark then light. Keep the first.
    seen, unique = set(), []
    for ident, name, at in found:
        if ident not in seen:
            seen.add(ident)
            unique.append((ident, name, at))
    return unique


def describe(doc: str, start: int, limit: int = 11000) -> list[tuple[str, str, str]]:
    rows = []
    for tag, style, text in ELEMENT.findall(doc[start : start + limit]):
        label = html.unescape(text).strip()
        rows.append((tag, label, tidy(style)))
    return rows


def main() -> int:
    source = boards()
    if not source.is_dir():
        print(f"No boards at {source}", file=sys.stderr)
        return 1

    print(f"Reading {source.relative_to(ROOT)}")
    OUT.mkdir(parents=True, exist_ok=True)
    total = 0

    for board in sorted(source.glob("*.dc.html")):
        doc = board.read_text(encoding="utf-8", errors="replace")
        found = screens(doc)
        if not found:
            continue

        name = board.stem.replace(".dc", "")
        lines = [
            f"# {name} — measurements",
            "",
            "GENERATED by `scripts/extract-design.py`. Do not edit.",
            "",
            "Every value is taken straight from the drawn screen, which is why this",
            "is the thing to build against rather than a remembered token. Where a",
            "figure here disagrees with `07-design-tokens.md`, the token doc states",
            "the intent and this states what was actually drawn.",
            "",
            f"{len(found)} screens.",
            "",
        ]

        for ident, title, at in found:
            lines += [f"## {ident} · {title}", "", "| tag | text | style |", "|---|---|---|"]
            for tag, text, style in describe(doc, at):
                cell = style.replace("|", "\\|")
                lines.append(f"| `{tag}` | {text or '—'} | `{cell}` |")
            lines.append("")

        (OUT / f"{name}.md").write_text("\n".join(lines), encoding="utf-8")
        print(f"  {name}: {len(found)} screens")
        total += len(found)

    print(f"Wrote {total} screen specs to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
